Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      ImageId: ami-0742b4e673072066f
      Tags:
        - 
          Key: "Environment"
          Value: "ModernizationWorkshop"
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22 test 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
       - 
          Key: "Environment"
          Value: "ModernizationWorkshop"
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fiona-modernization-workshop
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
        - 
          Key: "Environment"
          Value: "ModernizationWorkshop"